http_port 3129
http_port 3128 intercept

acl localnet src 192.168.3.0/24

# Heures de bureau (calculees en UTC : Madagascar = UTC+3)
# 08:00-12:00 locale -> 05:00-09:00 UTC
# 14:00-18:00 locale -> 11:00-15:00 UTC
acl heures_bureau_matin time 05:00-09:00
acl heures_bureau_apresmidi time 11:00-15:00

acl reseaux_sociaux dstdomain .facebook.com .youtube.com

acl sites_adultes dstdomain "/etc/squid/blacklist_adultes.txt"

http_access deny sites_adultes
http_access deny reseaux_sociaux heures_bureau_matin
http_access deny reseaux_sociaux heures_bureau_apresmidi

http_access allow localnet
http_access allow localhost
http_access deny all
